spring.application.name=monday-backend
spring.profiles.active=${APP_ENV}
server.port=8080

# ===============================
# = Spring Security (Optional) =
# ===============================

# Enable stateless JWT auth (if using)
#spring.security.oauth2.resourceserver.jwt.issuer-uri=https://your-issuer.com/

jwt.secret=${JWT_SECRET}
jwt.expiration=3600000

app.security.devBypass=${DEV_BYPASS:true}

#jwt | opaque | dev
# jwt provides ISSUER/AUDIENCE/JWKSURI via env
app.security.mode=jwt
app.security.jwksUri=https://auth.example.com/.well-known/jwks.json
app.security.issuer=https://auth.example.com/
app.security.audience=mondaymemory


# ===============================
# = Database Configuration      =
# ===============================

# Database connection settings
spring.datasource.url=${DB_URL:jdbc:h2:mem:testdb}
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=${DB_DRIVER_CLASS:org.h2.Driver}

# Hibernate (JPA) properties
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.database-platform=${DB_PLATFORM}
spring.h2.console.enabled=true

# ===============================
# = Scheduled Tasks             =
# ===============================

spring.task.scheduling.pool.size=10
spring.task.scheduling.thread-name-prefix=scheduled-task-

# ===============================
# = Elasticsearch repos         =
# ===============================
spring.data.elasticsearch.repositories.enabled=false

# ===============================
# = Logging                     =
# ===============================

logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
# Logging level
logging.level.root=INFO
logging.level.com.monday.monday_backend=DEBUG
