CREATE TABLE users (
    user_id UUID PRIMARY KEY,
    email VARCHAR(320),
    display_name VARCHAR(255),
    linked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE payment_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255),
    type VARCHAR(255),
    stripe_event_id VARCHAR(255) NOT NULL,
    received_at TIMESTAMP WITH TIME ZONE NOT NULL,
    payload_json CLOB
);

ALTER TABLE payment_event
    ADD CONSTRAINT uk_payment_event_stripe_event_id
        UNIQUE (stripe_event_id);


CREATE TABLE role_entity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    access_level VARCHAR(255) NOT NULL,
    CONSTRAINT uk_role_entity_access_level UNIQUE (access_level)
);

CREATE TABLE price_plan (
    id UUID PRIMARY KEY,
    code VARCHAR(255) NOT NULL,
    stripe_price_id VARCHAR(255) NOT NULL,
    display_name VARCHAR(255),
    monthly_amount INTEGER,
    annual_amount INTEGER,
    max_topics_per_period INTEGER,
    max_tokens_per_period INTEGER,
    warning_threshold_ratio BIGINT,
    CONSTRAINT uk_price_plan_code UNIQUE (code)
);


CREATE TABLE user_roles (
    user_id UUID NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_user_roles_role
        FOREIGN KEY (role_id) REFERENCES role_entity(id)
);


CREATE TABLE user_plan (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL,
    price_plan_id UUID,
    stripe_customer_id VARCHAR(255),
    stripe_subscription_id VARCHAR(255),
    current_period_end TIMESTAMP,
    updated_at TIMESTAMP NOT NULL,
    period_start TIMESTAMP,
    period_end TIMESTAMP,
    topics_used INTEGER,
    tokens_used BIGINT,
    version BIGINT NOT NULL,

    CONSTRAINT fk_user_plan_user
        FOREIGN KEY (user_id) REFERENCES users(user_id),

    CONSTRAINT fk_user_plan_price_plan
        FOREIGN KEY (price_plan_id) REFERENCES price_plan(id),

    CONSTRAINT uk_user_plan_user_id
        UNIQUE (user_id),

    CONSTRAINT uk_user_plan_stripe_customer_id
        UNIQUE (stripe_customer_id)
);

