-- Users
CREATE TABLE IF NOT EXISTS users (
    user_id UUID PRIMARY KEY,
    email VARCHAR(320),
    display_name VARCHAR(255),
    linked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email)
);

-- Roles (assuming your RolesEntity maps to role_entity(id, access_level))
CREATE TABLE IF NOT EXISTS role_entity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    access_level VARCHAR(255) NOT NULL,
    CONSTRAINT uk_role_entity_access_level UNIQUE (access_level)
);

-- User ↔ Roles join table
CREATE TABLE IF NOT EXISTS user_roles (
    user_id UUID NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_role
        FOREIGN KEY (role_id) REFERENCES role_entity(id) ON DELETE CASCADE
);

-- Helpful indexes (optional but smart)
CREATE INDEX IF NOT EXISTS ix_users_email ON users(email);
CREATE INDEX IF NOT EXISTS ix_user_roles_role_id ON user_roles(role_id);


CREATE TABLE payment_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    type VARCHAR(255) NOT NULL,
    stripe_event_id VARCHAR(255) NOT NULL,
    received_at TIMESTAMP WITH TIME ZONE NOT NULL,
    payload_json TEXT,
    CONSTRAINT uk_payment_event_stripe_event_id UNIQUE (stripe_event_id),
    CONSTRAINT fk_payment_event_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);


CREATE TABLE IF NOT EXISTS price_plan (
    id UUID PRIMARY KEY,

    code VARCHAR(255) NOT NULL,
    stripe_price_id VARCHAR(255) NOT NULL,

    display_name VARCHAR(255),
    monthly_amount INTEGER,
    annual_amount INTEGER,

    max_topics_per_period INTEGER,
    max_tokens_per_period BIGINT,

    warning_threshold_ratio DOUBLE PRECISION,

    CONSTRAINT uk_price_plan_code UNIQUE (code),
    CONSTRAINT uk_price_plan_stripe_price_id UNIQUE (stripe_price_id)
);

-- Optional but useful (lookup by code is common)
CREATE INDEX IF NOT EXISTS ix_price_plan_code ON price_plan(code);


CREATE TABLE IF NOT EXISTS user_plan (
    id UUID PRIMARY KEY,

    user_id UUID NOT NULL,
    price_plan_id UUID,

    stripe_customer_id VARCHAR(255),
    stripe_subscription_id VARCHAR(255),

    current_period_end TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

    period_start TIMESTAMP WITH TIME ZONE,
    period_end TIMESTAMP WITH TIME ZONE,

    topics_used INTEGER,
    tokens_used BIGINT,

    version BIGINT NOT NULL,

    CONSTRAINT fk_user_plan_user
        FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,

    CONSTRAINT fk_user_plan_price_plan
        FOREIGN KEY (price_plan_id) REFERENCES price_plan(id),

    CONSTRAINT uk_user_plan_user_id
        UNIQUE (user_id),

    CONSTRAINT ix_user_plan_customer_id
        UNIQUE (stripe_customer_id)
);

-- Optional but useful for subscription lookups (Stripe subscription id is frequently queried)
CREATE INDEX IF NOT EXISTS ix_user_plan_subscription_id
    ON user_plan(stripe_subscription_id);


ALTER TABLE user_plan
    ADD CONSTRAINT uk_user_plan_stripe_subscription_id UNIQUE (stripe_subscription_id);


