-- -------------------------
-- payment_events
-- -------------------------
CREATE TABLE payment_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    type VARCHAR(255) NOT NULL,
    stripe_event_id VARCHAR(255) NOT NULL,
    received_at TIMESTAMP WITH TIME ZONE NOT NULL,
    payload_json TEXT,
    CONSTRAINT uk_payment_event_stripe_event_id UNIQUE (stripe_event_id),
    CONSTRAINT fk_payment_event_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- -------------------------
-- price_plan
-- -------------------------
CREATE TABLE price_plan (
    id UUID PRIMARY KEY,

    code VARCHAR(255) NOT NULL,
    stripe_price_id VARCHAR(255) NOT NULL,

    display_name VARCHAR(255),
    monthly_amount INTEGER,
    annual_amount INTEGER,

    max_topics_per_period INTEGER,
    max_tokens_per_period BIGINT,

    warning_threshold_ratio DOUBLE PRECISION,

    CONSTRAINT uk_price_plan_code UNIQUE (code),
    CONSTRAINT uk_price_plan_stripe_price_id UNIQUE (stripe_price_id)
);

-- Optional but useful (lookup by code is common)
CREATE INDEX ix_price_plan_code ON price_plan(code);


-- -------------------------
-- user_plan
-- -------------------------
CREATE TABLE user_plan (
    id UUID PRIMARY KEY,

    user_id UUID NOT NULL,
    price_plan_id UUID,

    stripe_customer_id VARCHAR(255),
    stripe_subscription_id VARCHAR(255),

    current_period_end TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

    period_start TIMESTAMP WITH TIME ZONE,
    period_end TIMESTAMP WITH TIME ZONE,

    topics_used INTEGER,
    tokens_used BIGINT,

    version BIGINT NOT NULL,

    CONSTRAINT fk_user_plan_user
        FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,

    CONSTRAINT fk_user_plan_price_plan
        FOREIGN KEY (price_plan_id) REFERENCES price_plan(id),

    CONSTRAINT uk_user_plan_user_id
        UNIQUE (user_id),

    CONSTRAINT ix_user_plan_customer_id
        UNIQUE (stripe_customer_id)
);

-- Optional but useful for subscription lookups (Stripe subscription id is frequently queried)
CREATE INDEX ix_user_plan_subscription_id
    ON user_plan(stripe_subscription_id);

ALTER TABLE user_plan
    ADD CONSTRAINT uk_user_plan_stripe_subscription_id UNIQUE (stripe_subscription_id);