-- -------------------------
-- role
-- -------------------------
CREATE TABLE role_entity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    access_level VARCHAR(255) NOT NULL,
    CONSTRAINT uk_role_entity_access_level UNIQUE (access_level)
);

-- User ↔ Roles join table
CREATE TABLE user_roles (
    user_id UUID NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_role
        FOREIGN KEY (role_id) REFERENCES role_entity(id) ON DELETE CASCADE
);

-- Helpful indexes (optional but smart)
CREATE INDEX ix_users_email ON users(email);
CREATE INDEX ix_user_roles_role_id ON user_roles(role_id);